### ISSUE TITLE
Exit code is 0 although state is critical because OCSP response expired

### ISSUE THREAD

**Issue by goldzahn** [patf/check-ocsp-stapling#1]
Hi Patrick,

I think there is a small bug that hit me while testing OSCP Stapling:

if ($hoursLeft < 0) {
  print "$PROGNAME: CRITICAL - OCSP response expired " . abs($hoursLeft) . " hour(s) ago.\n";
} elsif ($hoursLeft <= $critical) {

-> after the print command there is the "exit $ERRORS{'CRITICAL'};" missing, so that exit code is 0 although the response expired and the state is critical.

Regards
Tim

**Comment by pfigel** [comment]
Thanks for the report! This should be fixed now.

Apologies for the insufficient testing - OCSP responses are a pain to mock. 🙁
